### ISSUE TITLE
No communication

### ISSUE THREAD

**Issue by shaxik1** [davedehaan/GoodBot#9]
Hello, I tried to set up everything according to your guide and It still cant communicate with google spreadsheet. I shared my spreadsheet with **discord@api-project-483394155093.iam.gserviceaccount.com** but google replied me, that this domain doesent exists and that why message wasnt deliver.
bot on discord seems set right, but still have blank google spreadsheet

**Comment by davedehaan** [comment]
hey @shaxik1 -- hop on my discord (goodbot.mankrikpugs.com) and I'll hop on your discord and help you out there.
